image: node:latest

stages:
  - build
  - test

building:
  stage: build
  script: 
        - npm install 

  artifacts:
    paths:
      - ./       

testing:
  stage: test
  script:
        - npm test
